name : " Multi Event Pipe Line"

on: 
    push:
        branches:
            - main
            - test

    pull_request:
        branches: 
            - main

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main push"
              run: echo " Running on main push"

    on-pull-request:
         runs-on: ubuntu-latest
         steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
